name: CI

on:
  push:
  workflow_dispatch:

run-name: Build & Test

jobs:
  CI:
    name: ci
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & Test
        run: mvn --batch-mode --update-snapshots verify